In [2]:
import numpy as np
import scipy as sp
import scipy.sparse as spsp

## Partie 1. (Format Compressed Sparse Row)


1.

In [4]:
row = np.array([0, 0, 1, 2, 2, 2])
col = np.array([0, 2, 2, 0, 1, 2])
data = np.array([1, 2, 3, 4, 5, 6])
A = spsp.csr_matrix((data, (row, col)), shape=(3, 3))

print("A.toarray() =\n", A.toarray())

A.toarray() =
 [[1 0 2]
 [0 0 3]
 [4 5 6]]


In [5]:
print("A =\n", A)

A =
   (0, 0)	1
  (0, 2)	2
  (1, 2)	3
  (2, 0)	4
  (2, 1)	5
  (2, 2)	6


2.

In [6]:
print("A[0, :] =\n", A[0, :])

A[0, :] =
   (0, 0)	1
  (0, 2)	2


3.

4.

## Partie 2. (Factorisation LU)

5.

6.

7.

## Partie 3 (Remplissage - fill in).

8.

9.

10.

## Partie 4 (temps de calcul).

11.

12.

13.